"""add deploy_branch to users

Revision ID: 62cad5c4cb44
Revises: 9f3021b89fdf
Create Date: 2026-08-15 19:57:29.628590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cad5c4cb44'
down_revision: Union[str, Sequence[str], None] = '9f3021b89fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deploy_branch', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deploy_branch')
    # ### end Alembic commands ###
