"""add_repo_reports_table

Revision ID: 95780adea624
Revises: 62cad5c4cb44
Create Date: 2026-09-12 19:41:00.444943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95780adea624'
down_revision: Union[str, Sequence[str], None] = '62cad5c4cb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('repo_full_name', sa.String(length=512), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_reports_id'), 'repo_reports', ['id'], unique=False)
    op.create_index(op.f('ix_repo_reports_repo_full_name'), 'repo_reports', ['repo_full_name'], unique=False)
    op.create_index('ix_repo_reports_user_generated', 'repo_reports', ['user_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_repo_reports_user_id'), 'repo_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_reports_user_id'), table_name='repo_reports')
    op.drop_index('ix_repo_reports_user_generated', table_name='repo_reports')
    op.drop_index(op.f('ix_repo_reports_repo_full_name'), table_name='repo_reports')
    op.drop_index(op.f('ix_repo_reports_id'), table_name='repo_reports')
    op.drop_table('repo_reports')
    # ### end Alembic commands ###
