"""add github token fields to users

Revision ID: 9f3021b89fdf
Revises: 61fec428af4e
Create Date: 2026-07-05 18:21:53.920609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3021b89fdf'
down_revision: Union[str, Sequence[str], None] = '61fec428af4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_token_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('github_scope', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'github_scope')
    op.drop_column('users', 'github_token_type')
    op.drop_column('users', 'github_token')
    # ### end Alembic commands ###
