"""Add deployments and agent tables

Revision ID: 9f8ae6414de0
Revises: 7f09806a3b0b
Create Date: 2026-09-19 00:57:37.542566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8ae6414de0'
down_revision: Union[str, Sequence[str], None] = '7f09806a3b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_state'), 'agent_sessions', ['state'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False)
    op.alter_column('users', 'render_api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'render_owner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'render_owner_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'render_api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_messages_user_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_state'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
