"""Add deployments table

Revision ID: dece5564cf24
Revises: 9f8ae6414de0
Create Date: 2026-09-19 00:59:16.763945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dece5564cf24'
down_revision: Union[str, Sequence[str], None] = '9f8ae6414de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('external_deploy_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_deployments_external_deploy_id'), 'deployments', ['external_deploy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_external_deploy_id'), table_name='deployments')
    op.drop_column('deployments', 'external_deploy_id')
    # ### end Alembic commands ###
